[program:pytracking]
command=/home/pytracking/pytracking/venv/bin/gunicorn -w 4 -b 127.0.0.1:8000 app:app
directory=/home/pytracking/pytracking
user=pytracking
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=600
killasgroup=true
priority=998
environment=PATH="/home/pytracking/pytracking/venv/bin"
stdout_logfile=/var/log/supervisor/pytracking.log
stderr_logfile=/var/log/supervisor/pytracking_error.log
